### ISSUE TITLE
deploy failed

### ISSUE THREAD

**Issue by LengYuna** [SDUOJ/OnlineJudge#3]
**Describe the bug**
Login failed
I tried to restart many times, but the problem still arose

**Environment:**

OS: Ubuntu 20.04
CPU: [6 Core]
RAM: [8 GB]
Disk: [900 GB]
Docker Version: [20.10.5]
Docker-Compose Version: [1.28.5]

**Additional context**

![QQ截图20210320232713](https://user-images.githubusercontent.com/48179733/111875472-ee5bd580-89d4-11eb-81f2-59eafa1069c0.png)

**Comment by LengYuna** [comment]
I like your project very much. I think **SDUOJ** is very outstanding. I especially like its competition ranking interface and related functions.

Sincerely hope you can launch a new version as soon as possible, I can't wait for this, come on!

**Comment by zhangt2333** [comment]
Thanks! 

I haven't updated the repo `sduoj-deploy` for a long time so that maybe something wrong in one-click deployment.

Because of the busy study schedule, I has not release a stable version of SDUOJ.

I will update `sduoj-deploy` in next week. However, I don't recommend using SDUOJ for actual production use until we release a stable version.

**Comment by zhangt2333** [comment]
OK. Now `sduoj-deploy` provide a trial version of SDUOJ, whose docker-image won't be triggered update on commit.
> * https://github.com/SDUOJ/sduoj-web/tree/stable
> * https://github.com/SDUOJ/sduoj-manage/tree/stable
> * https://github.com/SDUOJ/sduoj-server/tree/stable
> * https://github.com/SDUOJ/sduoj-deploy/commit/c6a28420609591c6e4df194f43f0c06656c676dd
> * https://github.com/SDUOJ/sduoj-deploy/commit/3d33f482e5fd3e60d51cb1185586eb1f49d283b7
