### ISSUE TITLE
Is GPL v3.0 license enough?

### ISSUE THREAD

**Issue by SadPencil** [SDUOJ/OnlineJudge#5]
Since this is an online web service, malicious developers could compile and run this project without sharing the source code he has changed, while not against GPL v3.0.

You should use AGPL v3.0 to stop others doing evil things.

**Comment by zhangt2333** [comment]
Aha, I saw today that an open source developer deleted his code and made the community a mess. ([link1](https://www.zhihu.com/question/510180628), [link2](https://www.thegingerviking.com/the-right-to-delete-fakerjs-fragile-nature-open-source/))

It reminded me that we open source SDUOJ to share solutions of our own, in order to have more participation and discussion.

Hey old chap @jesHrz, do you think it's a good idea to replace the current GPL license with a stronger AGPL?

**Comment by jesHrz** [comment]
Ok that is quite a potential risk, and I agree to change the license to AGPL.

First, it is our duty to stop bad apples using our ideas to do evil things which are not against GPL license. And second, we don't want to see someone possesses our ideas as their own. 

We share our ideas and we also hope others can share theirs too!

**Comment by zhangt2333** [comment]
I think that everything is ok.

Thank you @SadPencil, now I'd like to close this issue.
